/**
 * This class is generated by jOOQ
 */
package com.picc.entity.targetplan;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "userinfo", schema = "test_1")
public class Userinfo implements Serializable {

	private static final long serialVersionUID = -1729350394;

	private Integer  id;
	private String   name;
	private Integer age;

	public Userinfo() {}

	public Userinfo(Userinfo value) {
		this.id = value.id;
		this.name = value.name;
		this.age = value.age;
	}

	public Userinfo(
		Integer  id,
		String   name,
		Integer age
	) {
		this.id = id;
		this.name = name;
		this.age = age;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", nullable = false, precision = 10)
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}
}
